export interface User {
    _id?: string,
    name: string,
    lastname: string,
    username?: string,
    password?:string,
    f_create:string,
    photo?: string,
    birth: string,
    state: string,
    city: string,
    address: string,
    telephone: string,
    cellphone:string,
    brand: string,
    year: string,
    model:string,
    car_plate: string,
    type?: string
  }